name: Build & Cache NixOS Artifacts

on:
  push:
    branches:
        - flakes
  workflow_run:
    workflows:
        - "Update flake.lock"
    types:
        - completed

jobs:
  build-and-cache:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && 'update_flake_lock_action' || github.ref }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
            endpoint: ${{ secrets.ATTIC_SERVER }}
            token: ${{ secrets.ATTIC_TOKEN }}
            cache: nixos

      - name: Build all NixOS configurations
        run: |
          configs=$(nix flake show --json . | jq -r '.nixosConfigurations | keys[]')

          for cfg in $configs; do
            echo "▶️ Building $cfg"
            nix build .#nixosConfigurations."$cfg".config.system.build.toplevel
          done
